
service: awsassignment

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  profile: serverlessUser
  stage: dev
  region: eu-north-1
  environment:
    tableName: ${self:custom.tableName}
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "dynamodb:*"
          Resource: '*'  

custom:
  tableName: assignment-users

functions:
  getUserById:
    handler: lambdas/endpoints/getUserById.handler
    events:
      - http:
          path: get-user-by-id/{ID}
          method: GET
          cors: true

resources:
  Resources:
    MyDynamoDbTable:
      Type: AWS::DynamoDB::Table
      Properties: 
        TableName: ${self:custom.tableName}
        AttributeDefinitions: 
          - AttributeName: ID
            AttributeType: S
        KeySchema: 
          - AttributeName: ID
            KeyType: HASH 
        BillingMode: PAY_PER_REQUEST
